-- ============================================================================
-- 0000_base · leads_sistema (captação do site legado)
-- ----------------------------------------------------------------------------
-- Por que existe: esta tabela nunca esteve em nenhum .sql do repo — foi criada
-- à mão pelo painel do Supabase no projeto antigo. As migrations 0014, 0015,
-- 0018 e 0023 a referenciam, então num projeto vazio a migração morre.
-- Colunas reconstruídas de src/integrations/supabase/types.ts (gerado do banco
-- real), preservando nomes exatos — inclusive os tortos — porque o client
-- tipado depende deles: `endereco_gandu` (é bairro), `med_numereo_convenio`,
-- e os acentuados `gênero` / `indicações`. Renomear aqui quebra o app.
--
-- SEGURANÇA: no projeto antigo esta tabela ficou SEM RLS e a anon key (pública,
-- embutida no bundle) lia CPF, RG, nascimento, endereço, convênio e alergias de
-- todo mundo — confirmado em 06/08/2026. Aqui ela nasce trancada: RLS ligado +
-- FORCE, e a única policy é INSERT (o formulário público). Leitura é exclusiva
-- da service_role, que ignora RLS. Não afrouxar sem decidir quem lê.
-- Roda ANTES de 0000_bootstrap_base.sql.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.leads_sistema (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_lead               TEXT,
  nome                  TEXT,
  email                 TEXT,
  telefone              BIGINT,
  cpf                   BIGINT,
  rg                    BIGINT,
  data_nascimento       TEXT,
  "gênero"              TEXT,
  endereco_cep          TEXT,
  endereco_logradouro   TEXT,
  endereco_numero       BIGINT,
  endereco_complemento  TEXT,
  endereco_gandu        TEXT,
  endereco_estado       TEXT,
  med_nome_convenio     TEXT,
  med_numereo_convenio  BIGINT,
  med_sanguineo         TEXT,
  med_alergias          TEXT,
  atendimento_com_ia    TEXT,
  etiquetas             TEXT,
  "indicações"          TEXT,
  observacoes           TEXT,
  origem                TEXT,
  numero_clinica        BIGINT,
  criado_em             TIMESTAMPTZ DEFAULT NOW()
);

-- Tranca por padrão. FORCE faz valer até para o owner da tabela.
ALTER TABLE public.leads_sistema ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads_sistema FORCE ROW LEVEL SECURITY;

-- Formulário público: só grava, nunca lê. Sem policy de SELECT/UPDATE/DELETE,
-- o padrão do RLS é negar — anon fica sem qualquer forma de ler o que gravou.
DROP POLICY IF EXISTS leads_sistema_insert_publico ON public.leads_sistema;
CREATE POLICY leads_sistema_insert_publico ON public.leads_sistema
  FOR INSERT TO anon, authenticated WITH CHECK (true);
